### ISSUE TITLE
好像没法下载插件诶

### ISSUE THREAD

**Issue by wzq10314** [Lonely-Sails/nonebot-plugin-mc-watcher#1]
root@VM-4-11-ubuntu:~/nonebot11# nb plugin install nonebot_plugin_mc_watcher
Using python: /root/nonebot11/.venv/bin/python
Looking in indexes: http://mirrors.tencentyun.com/pypi/simple
ERROR: Could not find a version that satisfies the requirement nonebot_plugin_mc_watcher (from versions: none)
ERROR: No matching distribution found for nonebot_plugin_mc_watcher

**Comment by wzq10314** [comment]
更换源后解决了，但是还有有报错诶
10-08 17:43:07 [ERROR] nonebot | Failed to import "nonebot_plugin_mc_watcher"
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 203, in load_all_plugins
    return set(
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot_plugin_mc_watcher/__init__.py", line 22, in <module>
    config = get_plugin_config(Config)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/plugin/__init__.py", line 173, in get_plugin_config
    return type_validate_python(config, model_dump(get_driver().config))
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/compat.py", line 225, in type_validate_python
    return TypeAdapter(type_).validate_python(data)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 135, in wrapped
    return func(self, *args, **kwargs)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 366, in validate_python
    return self.validator.validate_python(object, strict=strict, from_attributes=from_attributes, context=context)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config
minecraft_servers
  Input should be a valid dictionary [type=dict_type, input_value='118.89.156.184', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/dict_type

**Comment by wzq10314** [comment]
10-08 18:12:48 [ERROR] nonebot | Failed to import "nonebot_plugin_mc_watcher"
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 203, in load_all_plugins
    return set(
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot_plugin_mc_watcher/__init__.py", line 22, in <module>
    config = get_plugin_config(Config)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/plugin/__init__.py", line 173, in get_plugin_config
    return type_validate_python(config, model_dump(get_driver().config))
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/compat.py", line 225, in type_validate_python
    return TypeAdapter(type_).validate_python(data)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 135, in wrapped
    return func(self, *args, **kwargs)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 366, in validate_python
    return self.validator.validate_python(object, strict=strict, from_attributes=from_attributes, context=context)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config
minecraft_servers
  Input should be a valid dictionary [type=dict_type, input_value=['127.0.0.1:24444'], input_type=list]
这个报错是env填错了嘛

**Comment by wzq10314** [comment]
emmmm用字典类型后发送/mc
10-08 18:51:46 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_mc_watcher, lineno=23) failed.
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot_plugin_mc_watcher/__init__.py", line 40, in _
    servers_motd = await fetch_all_motd(config.servers)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/pydantic/main.py", line 856, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'Config' object has no attribute 'servers'

**Comment by Lonely-Sails** [comment]
已在最新版本修复。
