### ISSUE TITLE
无法使用/mc ，也收不到玩家进出消息广播

### ISSUE THREAD

**Issue by Thedeergod666** [Lonely-Sails/nonebot-plugin-mc-watcher#2]
.env配置如下
minecraft_servers={"然日卡电台":"127.0.0.1:25565"} #要监控的服务器名称和对应的地址（一个字典）
minecraft_update_interval=30 #向 Minecraft 服务器发送 Motd 请求的间隔
minecraft_broadcast_server=True #是否广播服务器开启/关闭消息
minecraft_broadcast_player=True #是否广播服务器玩家离开/加入消息
minecraft_broadcast_groups=[114514] #广播的 QQ 群号列表（若为空则上面的两个不生效）

在qq在的群聊发送/mc后报错如下
11-30 19:38:48 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_mc_watcher, lineno=23) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "C:\Users\Administrator\Desktop\uu5u-bot\mc-bot\.venv\lib\site-packages\nonebot\__init__.py", line 337, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\uu5u-bot\mc-bot\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 188, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\uu5u-bot\mc-bot\.venv\lib\site-packages\uvicorn\main.py", line 579, in run
    server.run()
  File "C:\Users\Administrator\Desktop\uu5u-bot\mc-bot\.venv\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\uu5u-bot\mc-bot\.venv\lib\site-packages\nonebot\utils.py", line 254, in run_coro_with_shield
    return await coro
  File "C:\Users\Administrator\Desktop\uu5u-bot\mc-bot\.venv\lib\site-packages\nonebot\message.py", line 506, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\Administrator\Desktop\uu5u-bot\mc-bot\.venv\lib\site-packages\nonebot\message.py", line 458, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\uu5u-bot\mc-bot\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 900, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\uu5u-bot\mc-bot\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 837, in simple_run
    await handler(
  File "C:\Users\Administrator\Desktop\uu5u-bot\mc-bot\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\Desktop\uu5u-bot\mc-bot\.venv\lib\site-packages\nonebot_plugin_mc_watcher\__init__.py", line 40, in _
    servers_motd = await fetch_all_motd(config.minecraft_servers)
  File "C:\Users\Administrator\Desktop\uu5u-bot\mc-bot\.venv\lib\site-packages\nonebot_plugin_mc_watcher\minecraft.py", line 20, in fetch_all_motd
    return {name: await task for name, task in tasks.items()}
  File "C:\Users\Administrator\Desktop\uu5u-bot\mc-bot\.venv\lib\site-packages\nonebot_plugin_mc_watcher\minecraft.py", line 20, in <dictcomp>
    return {name: await task for name, task in tasks.items()}
  File "C:\Users\Administrator\Desktop\uu5u-bot\mc-bot\.venv\lib\site-packages\nonebot_plugin_mc_watcher\minecraft.py", line 47, in fetch_server_motd
    motd_data.pop('favicon')
KeyError: 'favicon'

**Comment by Lonely-Sails** [comment]
已在 v1.0.6 版本中修复。
